name: Deploy AI Archives to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.SERVER_HOST }}
      USER: ${{ secrets.SERVER_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Sync build to EC2
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key
          rsync -avz --delete \
            --exclude 'node_modules' --exclude '.git' --exclude '.env' \
            -e "ssh -i deploy_key -o StrictHostKeyChecking=no" \
            . $USER@$HOST:~/app

      - name: Restart AI Archives service
        run: |
          ssh -i deploy_key -o StrictHostKeyChecking=no $USER@$HOST \
            "sudo systemctl restart aiarchives"
